local DevTools = ModuleCore.Category:new("devtools", "DevTools")
DevTools:AddPage("objects", require("modules.devtools.objects"))
DevTools:AddPage("gui", require("modules.devtools.gui"))
-- DevTools:AddPage()
-- DevTools:AddPage()
-- DevTools:AddPage(ModuleCore.Page:new("Объекты"))
-- DevTools:AddPage(ModuleCore.Page:new("Пикапы"))
-- DevTools:AddPage(ModuleCore.Page:new("Текстдравы"))
-- DevTools:AddPage(ModuleCore.Page:new("Диалоги"))
-- DevTools:AddPage(ModuleCore.Page:new("3D Тексты"))
-- DevTools:AddPage(ModuleCore.Page:new("Чат"))