local DevTools = ModuleCore.Category:new("DevTools")
DevTools:AddPage(require("modules.devtools.objects"))
DevTools:AddPage(require("modules.devtools.gui"))
-- DevTools:AddPage()
-- DevTools:AddPage()
-- DevTools:AddPage(ModuleCore.Page:new("Объекты"))
-- DevTools:AddPage(ModuleCore.Page:new("Пикапы"))
-- DevTools:AddPage(ModuleCore.Page:new("Текстдравы"))
-- DevTools:AddPage(ModuleCore.Page:new("Диалоги"))
-- DevTools:AddPage(ModuleCore.Page:new("3D Тексты"))
-- DevTools:AddPage(ModuleCore.Page:new("Чат"))